### ISSUE TITLE
API call error 500 in menteeOrganizer

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#938]
During test qa automated we have found this api error

![image](https://github.com/hack4impact-uiuc/mentee/assets/35821871/ca0f3a38-00f3-4bb8-8abe-0f86118ff690)

**Comment by robert-dm** [comment]
@Humayun0008 could you pls confirm the steps to reproduce this error?

**Comment by Humayun0008** [comment]
@robert-dm @SolMon9099 I tried to reproduce is manually but its not reproducing by executing manual steps. However in automation case, It might be happening because in automation steps are executing so quickly that server respond with error code 500 and test case getting fail in automation because of that .

**Comment by robert-dm** [comment]
@Humayun0008 could you please fix in automation? thank you.

**Comment by Humayun0008** [comment]
> @Humayun0008 could you please fix in automation? thank you.

okay
